# Generated by Django 4.1.7 on 2023-05-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('IDnum', models.CharField(max_length=9)),
                ('birthDate', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('level', models.PositiveIntegerField()),
                ('dep', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
        ),
    ]
